steps:
  - name: Install backend dependencies
    run: cd todo_backend && npm install

  - name: Install frontend dependencies
    run: cd todo_frontend && npm install

  # - name: Run frontend tests
  #   run: cd todo_frontend && npm test

  # Uncomment if backend has tests
  # - name: Run backend tests
  #   run: cd todo_backend && npm test

deploy:
  frontend:
    path: todo_frontend/
    platform: vercel
    token: UfmhivOT5zQnogdwi6Cl0zA0

  backend:
    path: todo_backend/
    platform: render
    token: https://api.render.com/deploy/srv-abc123?key=YOUR_RENDER_KEY
