steps:
  - name: Install backend dependencies
    run: cd todo_backend && npm install

  - name: Install frontend dependencies
    run: cd todo_frontend && npm install

  # - name: Run frontend tests
  #   run: cd todo_frontend && npm test

  # Uncomment if backend has tests
  # - name: Run backend tests
  #   run: cd todo_backend && npm test

deploy:
  frontend:
    path: todo_frontend/
    platform: vercel
    token: htxu5lbpBMvys7qDbqZmZf4v

  backend:
    path: todo_backend/
    platform: render
    token: https://api.render.com/deploy/srv-d1r557ruibrs73f5niqg?key=1hCYQjGbv8c
